experiment:
  name: "baseline-run"
  model: "yolov8n-seg.pt"
dataset:
  path: "dataset-v2"
  img_size: 640
training:
  epochs: 150
  exist_ok: True # Overwrite the existing runs directory
  batch_size: 4 # num images per batch
  learning_rate: 0.001
  device: [0]
  amp: True # Automatic Mixed Precision
  freeze: None
  fraction: 1.0
  plots: True
  resume: False
benchmark:
  device: 0 # [0] or "cpu"
  img_size: 640
  fp16_quant: False
  int8_quant: False
  verbose: True
