experiment:
  name: "sanity-run"
  model: "yolov8n-seg.pt"
dataset:
  path: "dataset-v2"
  img_size: 640
training:
  epochs: 2
  exist_ok: True # Overwrite the existing runs directory
  batch_size: 16 # num images per batch
  # batch_size: 0.5 # 50% of the available GPU memory [Auto-mode with Utilization Fraction]
  learning_rate: 0.001
  device: 'mps'
  amp: True # Automatic Mixed Precision
  freeze: None
  fraction: 0.3
  plots: True
  resume: False
benchmark:
  device: 0 # [0] or "cpu"
  img_size: 640
  fp16_quant: False
  int8_quant: False
  verbose: True